import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { WalletSelect } from '@talismn/connect-components'
import { Wallet, WalletAccount } from '@talismn/connect-wallets'
import { cryptoWaitReady, decodeAddress, signatureVerify } from '@polkadot/util-crypto'
import { u8aToHex } from '@polkadot/util'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [ wallet, setWallet ] = useState<Wallet | null>(null)
  const [ accounts, setAccounts ] = useState<WalletAccount[]>([])

  useEffect(() => {
    console.log('wallet', wallet)
    console.log('accounts', accounts)

    if (wallet && accounts.length > 0) {
      wallet.signer.signRaw({
        type: 'payload',
        data: 'Some data to sign...',
        address: accounts[0].address,
      })
      .then(async ({ signature }: { signature: string }) => {
        await cryptoWaitReady();
        const isValid = isValidSignature(
          'Some data to sign...',
          signature,
          accounts[0].address
        );
        console.log(isValid)
      })
    }
  }, [wallet, accounts])

  const isValidSignature = (signedMessage: string, signature: string, address: string) => {
    const publicKey = decodeAddress(address);
    const hexPublicKey = u8aToHex(publicKey);
  
    return signatureVerify(signedMessage, signature, hexPublicKey).isValid;
  };

  return (
    <>
      <Head>
        <title>Web3 Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        <div>
          <WalletSelect
            dappName="My First Dapp"
            triggerComponent={
              <button
                onClick={(wallets) => {
                  // Do stuff with the supported wallets
                  console.log(wallets)
                }}
              >
                Connect to wallet
              </button>
            }
            onWalletConnectClose={() => console.log('onWalletConnectClose')}
            onWalletSelected={(wallet) => setWallet(wallet)}
            onUpdatedAccounts={(accounts) => setAccounts(accounts || [])}
            onAccountSelected={(account) => console.log('onAccountSelected', account)}
          />
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
